### ISSUE TITLE
Exception throw when opening some MIDI tracks

### ISSUE THREAD

**Issue by muiriswoulfe** [EnableIrelandAT/Coimbra#8] opened 2020-09-23 16:27 UTC
If you select some combinations of MIDI file and instrument, and then press either "Optimize for Keyboard" or "Optimize for Xbox", an exception is thrown from line 208 of ProjectCoimbra.UWP\Project.Coimbra\Pages\LaneSettingsPage.xaml.cs.

```
System.InvalidOperationException: 'Sequence contains no matching element'
```

The `AvailableKeys` object appears to be fine. Instead, the issue is with the list that is being constructed.

My understanding so far is that the issue occurs because there are no match notes under the given track and instrument. However, it is difficult for the user to work around this as they likely won't know the problematic combinations in advance. Therefore, we should try to filter out those instruments that don't work for keyboard and Xbox. And, even better, find tracks that cannot work at all and filter these out earlier.

**Comment by andreasbalzer** [comment] 2020-10-05 15:25
The cause was that some midi files don't specify the default instrument explicitly. We got this fixed now by specifying the default for channel without instruments.

**Closed as completed by andreasbalzer** 2020-10-05 15:25 UTC
